"""Fix migrations

Revision ID: 05670e23d93e
Revises: 30880f0b4efc
Create Date: 2025-09-24 15:35:27.767373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05670e23d93e'
down_revision = '30880f0b4efc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
