"""Add cascade delete for loan transactions

Revision ID: 1004b1983808
Revises: 2135538e90e4
Create Date: 2025-09-29 00:54:31.078545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1004b1983808'
down_revision = '2135538e90e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('loan_transactions_loan_id_fkey'), 'loan_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'loan_transactions', 'loans', ['loan_id'], ['loan_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan_transactions', type_='foreignkey')
    op.create_foreign_key(op.f('loan_transactions_loan_id_fkey'), 'loan_transactions', 'loans', ['loan_id'], ['loan_id'])
    # ### end Alembic commands ###
