"""Add missing columns to members

Revision ID: 17046807f9cd
Revises: 908336a671a8
Create Date: 2025-09-16 17:18:30.000639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17046807f9cd'
down_revision = '908336a671a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membership_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('oath_paper_url', sa.String(length=200), nullable=True),
    sa.Column('nid', sa.String(length=20), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('photo_url', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nid')
    )
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('gender')
        batch_op.drop_column('address')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('occupation')

    op.drop_table('membership_applications')
    # ### end Alembic commands ###
