"""Add member_id to audit_logs

Revision ID: 2135538e90e4
Revises: 05670e23d93e
Create Date: 2025-09-24 15:42:11.498128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2135538e90e4'
down_revision = '05670e23d93e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('member_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'audit_logs', 'members', ['member_id'], ['member_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'member_id')
    # ### end Alembic commands ###
