"""Remove reviewed_by column

Revision ID: 30880f0b4efc
Revises: 3e055487996c
Create Date: 2025-09-24 15:22:42.284899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30880f0b4efc'
down_revision = '3e055487996c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('loan_applications_reviewed_by_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'members', ['member_id'], ['member_id'], ondelete='CASCADE')
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loan_applications_reviewed_by_fkey'), 'admins', ['reviewed_by'], ['admin_id'])
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
