"""Fix cascade delete for models

Revision ID: 3eb9fb321a01
Revises: 2d1f8a8060ba
Create Date: 2025-09-24 15:06:58.353858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb9fb321a01'
down_revision = '2d1f8a8060ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('audit_logs_member_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('audit_logs_admin_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['admin_id'], ondelete='CASCADE')
        batch_op.drop_column('member_id')

    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('loan_applications_member_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['admin_id'], ondelete='CASCADE')
        batch_op.drop_column('member_id')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notifications_admin_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'admins', ['admin_id'], ['admin_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notifications_admin_id_fkey'), 'admins', ['admin_id'], ['admin_id'])

    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loan_applications_member_id_fkey'), 'members', ['member_id'], ['member_id'])
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('audit_logs_admin_id_fkey'), 'admins', ['admin_id'], ['admin_id'])
        batch_op.create_foreign_key(batch_op.f('audit_logs_member_id_fkey'), 'members', ['member_id'], ['member_id'])

    # ### end Alembic commands ###
