"""Added password_resets table and email column to admins

Revision ID: 419975de93ea
Revises: 1004b1983808
Create Date: 2025-10-02 13:46:34.107066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419975de93ea'
down_revision = '1004b1983808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.add_column('admins', sa.Column('email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'email')
    op.drop_table('password_resets')
    # ### end Alembic commands ###
