"""Initial KHG tables

Revision ID: 908336a671a8
Revises: 
Create Date: 2025-09-16 16:31:17.067846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908336a671a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('members',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('father_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('oath_paper_url', sa.String(length=200), nullable=True),
    sa.Column('nid', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('member_id'),
    sa.UniqueConstraint('nid')
    )
    op.create_table('vote_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_table', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('donations',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('donation_type', sa.String(length=50), nullable=True),
    sa.Column('donated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_table('loan_applications',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('amount_requested', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('loans',
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('approved_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('loan_id')
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_table('votes',
    sa.Column('vote_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('choice >= 0 AND choice <= 9', name='check_choice_range'),
    sa.ForeignKeyConstraint(['item_id'], ['vote_items.item_id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.member_id'], ),
    sa.PrimaryKeyConstraint('vote_id'),
    sa.UniqueConstraint('member_id', 'item_id', name='unique_member_vote')
    )
    op.create_table('loan_transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.loan_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loan_transactions')
    op.drop_table('votes')
    op.drop_table('notifications')
    op.drop_table('loans')
    op.drop_table('loan_applications')
    op.drop_table('donations')
    op.drop_table('audit_logs')
    op.drop_table('vote_items')
    op.drop_table('members')
    op.drop_table('admins')
    # ### end Alembic commands ###
