"""Added father_name column to membership_applications

Revision ID: a34dcfbc9b3d
Revises: 17046807f9cd
Create Date: 2025-09-16 20:29:21.306095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34dcfbc9b3d'
down_revision = '17046807f9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_applications', schema=None) as batch_op:
        batch_op.drop_column('father_name')

    # ### end Alembic commands ###
