"""add donation_type to donation_requests

Revision ID: bf5c7a8e077a
Revises: e056bb67c8ff
Create Date: 2025-10-06 01:03:44.333537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5c7a8e077a'
down_revision = 'e056bb67c8ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
