"""add donation_type to donation_requests

Revision ID: e056bb67c8ff
Revises: e5033eb82565
Create Date: 2025-10-06 01:02:47.251930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e056bb67c8ff'
down_revision = 'e5033eb82565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donation_requests', sa.Column('donation_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donation_requests', 'donation_type')
    # ### end Alembic commands ###
