"""Add full_name, photo_url, phone to Admin model

Revision ID: e2f2daae6c0d
Revises: fe475a24851d
Create Date: 2025-09-24 00:46:08.263250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2f2daae6c0d'
down_revision = 'fe475a24851d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('photo_url')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
