"""Add cause column to LoanApplication

Revision ID: fcdb448fbd8b
Revises: a34dcfbc9b3d
Create Date: 2025-09-18 00:06:56.549677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdb448fbd8b'
down_revision = 'a34dcfbc9b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cause', sa.Text(), nullable=True))

    with op.batch_alter_table('membership_applications', schema=None) as batch_op:
        batch_op.alter_column('father_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membership_applications', schema=None) as batch_op:
        batch_op.alter_column('father_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.drop_column('cause')

    # ### end Alembic commands ###
