"""Add application_id foreign keys to votes and vote_items

Revision ID: fe475a24851d
Revises: bb06516d9c53
Create Date: 2025-09-22 10:06:03.996676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe475a24851d'
down_revision = 'bb06516d9c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loan_applications', ['application_id'], ['application_id'])

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loan_applications', ['application_id'], ['application_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('application_id')

    with op.batch_alter_table('vote_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('application_id')

    # ### end Alembic commands ###
